### ISSUE TITLE
[BUG] Script will consistantly freeze at a seemingly arbitrary point when downloading saved posts

### ISSUE THREAD

**Issue by Nawor3565** [aliparlakci/bulk-downloader-for-reddit#465]
- [x] I am reporting a bug.
- [X] I am running the latest version of BDfR
- [X] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)
  
## Description
When running the script to download my saved posts, it will run fine until it tries to download a particular post. It won't throw an error, it will just sit there for at least hour with no progress. However, it still appears to be using small amount of internet bandwidth according to Task Manager. Exiting the script and running it again results it in freezing in the exact same spot. If I un-save the post it gets stuck on, it will freeze on the _next_ post after that. Weirdly, it seems like the file in question is actually fully downloaded, but for some reason the script will not continue or skip over the file.

## Command
```
python3.exe -m bdfr download "\\192.168.99.5\Sanguine\Active-Backups\Live" --user me --saved --authenticate --file-scheme '{POSTID}' --no-dupes --search-existing --config l_config.cfg
```

## Environment (please complete the following information):
 - OS: Win 10 21H1
 - Python version: 3.9.2

## Logs
The log contains NSFW links and titles, so I uploaded it here: https://paste.ee/p/ot3oD

**Comment by Soulsuck24** [comment]
#454 is the same issue. It seems to only (at least that I've seen) been Pornhub links that cause this lockup. I've just been manually adding them to my exclude file as they come up to move past them.

**Comment by Serene-Arc** [comment]
You can exclude pornhub as a domain as well @Soulsuck24. I'll get on this and see if I can find a cause and a fix.

**Comment by Soulsuck24** [comment]
> You can exclude pornhub as a domain as well @Soulsuck24. I'll get on this and see if I can find a cause and a fix.

That's been super hit and miss for me, I think because it's using the fallback downloader? But have tried to exclude it and it will still pop up from time to time.

**Comment by Serene-Arc** [comment]
@Soulsuck24 I just pushed a fix to the development branch for that. Youtube-dl is a little special in that we can't really run the download sequence at the same time as everything else, so the process is a little different. Instead of: look for the resource -> parse the url -> add to list -> download data, we have to do it differently: look for resource -> parse url -> download data -> add to list. 

I moved the domain filtering to be before that part so excluding pornhub completely should work now.

**Comment by Nawor3565** [comment]
@Serene-Arc I tried the updated dev version, but unfortunately it doesn't appear to have fixed it. The post the script gets stuck at isn't a PornHub link though, and if I unsave the post in question and re-save it (which moves the post to the top of the saved list), it will download it on the next run, but still get stuck in the same spot as before. This is similar to what LGSarge87 said in #454, since it seems to happen regardless of the type of media or host, but I'm at a loss since I don't know how to track down where exactly the problem lies (the website, reddit, my own system, etc).

**Comment by Serene-Arc** [comment]
@Nawor3565 if you can provide your logs then that would help. It's really hard to establish a pattern with posts like this so as many logs as possible would help.

**Comment by Nawor3565** [comment]
Okay, I think I figured it out. It looks like the fix DID actually work. The problem WAS with PornHub links, but (perhaps due to heavy rate-limiting by either the script or PH) it takes a long time to download, but does eventually complete now. I didn't realize that PH was the culprit because without the verbose option the console only prints the name of the file after it's been downloaded. Maybe making it print two lines per file, a "trying to download [file name]" when it starts and then a "download [file name]" message when it's finished? Just an idea. Regardless, it appears to be working fine now, it just requires some patience. Thanks for the quick fix!

**Comment by Serene-Arc** [comment]
@Nawor3565 in this case, we can't actually do that because we don't know what the file will be called until that stage is completed. The verbose logs do print out the submission ID which will let you find the Reddit page with a google search, which is how we investigate these things.

**Comment by Soulsuck24** [comment]
>  find the Reddit page with a google search

You can actually just reddit.com/POSTID and it will redirect for you.
